In [32]:
import pandas as pd

In [33]:
df_movies = pd.read_csv("IMDb movies.csv", low_memory=False)
df_ratings = pd.read_csv("IMDb ratings.csv")

In [34]:
# select columns

df_movies = df_movies[['imdb_title_id', 'title', 'year', 'genre', 'country']]
df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]

### 1. merge()

In [35]:
df1 = pd.DataFrame({
    'id': ['A','B','C','D'],
    'age': [30, 23, 25, 22]
})
df2 = pd.DataFrame({
    'id': ['C','D','E','F'],
    'job': ['Doctor', 'Statistician', 'Accountant', 'Developer']
})

### 1.1 Inner Join

In [36]:
df_inner_join = df1.merge(df2, on='id', how='inner')
df_inner_join

  id  age           job
0  C   25        Doctor
1  D   22  Statistician

In [37]:
#shape
print(df1.shape)
print(df2.shape)
print(df_inner_join.shape)

(4, 2)
(4, 2)
(2, 3)

### 1.1.1 Exercise

In [38]:
# merge the df_movies and df_ratings dataframes (inner join)

In [39]:
df_movies

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium"
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [40]:
df_ratings

      imdb_title_id  total_votes  mean_vote
0         tt0000009          154        5.9
1         tt0000574          589        6.3
2         tt0001892          188        6.0
3         tt0002101          446        5.3
4         tt0002130         2237        6.9
...             ...          ...        ...
85850     tt9908390          398        5.5
85851     tt9911196          724        7.9
85852     tt9911774          265        7.8
85853     tt9914286          194        9.4
85854     tt9914942          102        6.8

[85855 rows x 3 columns]

In [41]:
df_movies.merge(df_ratings, on='imdb_title_id', how='inner')

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [42]:
pd.merge(df_movies, df_ratings, on='imdb_title_id') # works the same as the previous code section

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

### 1.2 Outer join (Full join)

In [43]:
df_outer_join = df1.merge(df2, on='id', how='outer')
df_outer_join

  id   age           job
0  A  30.0           NaN
1  B  23.0           NaN
2  C  25.0        Doctor
3  D  22.0  Statistician
4  E   NaN    Accountant
5  F   NaN     Developer

In [44]:
# shape

print(df1.shape)
print(df2.shape)
print(df_inner_join.shape)
print(df_outer_join.shape)

(4, 2)
(4, 2)
(2, 3)
(6, 3)

### 1.2.1 Exercise

In [45]:
# merge df_movies and df_ratings (outer join)

In [46]:
df_movies.merge(df_ratings, on='imdb_title_id', how='outer')

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

### 1.3 Exclusive Outer join (Exclusive full join)

In [47]:
df1.merge(df2, on='id', how='outer', indicator=True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [48]:
# query

df_exclusive_outer_join = df1.merge(df2, on='id', how='outer', indicator=True).query("_merge=='left_only' or _merge=='right_only'")
df_exclusive_outer_join

  id   age         job      _merge
0  A  30.0         NaN   left_only
1  B  23.0         NaN   left_only
4  E   NaN  Accountant  right_only
5  F   NaN   Developer  right_only

In [49]:
# shape
print(df_exclusive_outer_join.shape)

(4, 4)

### 1.3.1 Exercise

In [50]:
# merge df_movies and df_ratings

df_movies.merge(df_ratings, on='imdb_title_id', how='outer', indicator=True)

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9,both
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3,both
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0,both
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3,both
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9,both
...,...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5,both
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9,both
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8,both
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4,both
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8,both

In [51]:

df_movies.merge(df_ratings, on='imdb_title_id', how='outer', indicator=True).query("_merge=='left_only' or _merge=='right_only'")

Empty DataFrame
Columns: [imdb_title_id, title, year, genre, country, total_votes, mean_vote, _merge]
Index: []

### 1.4 Left join

In [52]:
df1.merge(df2, on='id', how='left')

  id  age           job
0  A   30           NaN
1  B   23           NaN
2  C   25        Doctor
3  D   22  Statistician

### 1.4.1 Exercise

In [53]:
# extract a 50% sample of the df_movies dataframe

df_movies_sample = df_movies.sample(frac=0.5)
df_movies_sample

,imdb_title_id,title,year,genre,country
73016,tt3885696,Ice Cream,2014,"Horror, Thriller",India
73117,tt3907858,Sei mai stata sulla luna?,2015,Comedy,Italy
76378,tt4982252,Lone Wolves,2016,"Action, Sci-Fi",Australia
3052,tt0030473,La morte invisibile,1938,"Adventure, Crime, Drama",USA
83843,tt8160262,El Hijo,2019,Thriller,Argentina
...,...,...,...,...,...
55816,tt1234559,Chico Xavier,2010,"Biography, Drama",Brazil
31209,tt0120623,A Bug's Life - Megaminimondo,1998,"Animation, Adventure, Comedy",USA
73519,tt4045666,Mumbai Delhi Mumbai,2014,"Comedy, Romance",India
83720,tt8076418,Asuravadham,2018,"Action, Drama",India
45202,tt0401410,Gwai ma kwong seung kuk,2004,Comedy,Hong Kong

In [54]:
# merge df_movies_sample and df_ratings (left join)

df_left = df_movies_sample.merge(df_ratings, on='imdb_title_id', how='left')
df_left

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt3885696,Ice Cream,2014,"Horror, Thriller",India,113,4.4
1,tt3907858,Sei mai stata sulla luna?,2015,Comedy,Italy,1040,6.2
2,tt4982252,Lone Wolves,2016,"Action, Sci-Fi",Australia,159,2.5
3,tt0030473,La morte invisibile,1938,"Adventure, Crime, Drama",USA,903,6.3
4,tt8160262,El Hijo,2019,Thriller,Argentina,2802,5.3
...,...,...,...,...,...,...,...
42923,tt1234559,Chico Xavier,2010,"Biography, Drama",Brazil,1678,7.3
42924,tt0120623,A Bug's Life - Megaminimondo,1998,"Animation, Adventure, Comedy",USA,261431,7.3
42925,tt4045666,Mumbai Delhi Mumbai,2014,"Comedy, Romance",India,318,6.4
42926,tt8076418,Asuravadham,2018,"Action, Drama",India,256,6.6
42927,tt0401410,Gwai ma kwong seung kuk,2004,Comedy,Hong Kong,296,5.3

In [55]:
# shape

print(df_movies_sample.shape)
print(df_ratings.shape)
print(df_left.shape)

(42928, 5)
(85855, 3)
(42928, 7)

### 1.5 Exclusive Left join

In [ ]:
df1.merge(df2, on='id', how='outer', indicator=True).query("_merge=='left_only'")

  id   age  job     _merge
0  A  30.0  NaN  left_only
1  B  23.0  NaN  left_only

### 1.5.1 Exercise

In [57]:
# make a copy of the df_movies dataframe 

df_movies_2 = df_movies.copy()

df_movies_2

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium"
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [61]:
# set the first 1000 values of 'imdb_title_id' column as tt1234567890

df_movies_2.loc[:999, 'imdb_title_id'] = 'tt1234567890'
df_movies_2

,imdb_title_id,title,year,genre,country
0,tt1234567890,Miss Jerry,1894,Romance,USA
1,tt1234567890,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt1234567890,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt1234567890,Cleopatra,1912,"Drama, History",USA
4,tt1234567890,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium"
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [67]:
# merge df_movies_2 and df_ratings (exclusive left join)

df_exclusive_left = df_movies_2.merge(df_ratings, on='imdb_title_id', how='outer', indicator=True).query("_merge=='left_only'")
df_exclusive_left

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
55817,tt1234567890,Miss Jerry,1894,Romance,USA,NaN,NaN,left_only
55818,tt1234567890,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,NaN,NaN,left_only
55819,tt1234567890,Den sorte drøm,1911,Drama,"Germany, Denmark",NaN,NaN,left_only
55820,tt1234567890,Cleopatra,1912,"Drama, History",USA,NaN,NaN,left_only
55821,tt1234567890,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...
56812,tt1234567890,Agente segreto Z1,1930,Drama,USA,NaN,NaN,left_only
56813,tt1234567890,Tom Sawyer,1930,"Adventure, Comedy, Drama",USA,NaN,NaN,left_only
56814,tt1234567890,Tonka Sibenice,1930,Drama,"Czechoslovakia, Germany",NaN,NaN,left_only
56815,tt1234567890,Top Speed,1930,"Comedy, Musical, Romance",USA,NaN,NaN,left_only
56816,tt1234567890,True to the Navy,1930,"Action, Comedy, Romance",USA,NaN,NaN,left_only

In [69]:
# shape

print(df_exclusive_left.shape)
print(df_movies_2.shape)
print(df_ratings.shape)

(1000, 8)
(85855, 5)
(85855, 3)