In [120]:
import pandas as pd

In [121]:
df_movies = pd.read_csv("IMDb movies.csv", low_memory=False)
df_ratings = pd.read_csv("IMDb ratings.csv")

In [122]:
# select columns

df_movies = df_movies[['imdb_title_id', 'title', 'year', 'genre', 'country']]
df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]

### 1. merge()

In [123]:
df1 = pd.DataFrame({
    'id': ['A','B','C','D'],
    'age': [30, 23, 25, 22]
})
df2 = pd.DataFrame({
    'id': ['C','D','E','F'],
    'job': ['Doctor', 'Statistician', 'Accountant', 'Developer']
})

### 1.1 Inner Join

In [124]:
df_inner_join = df1.merge(df2, on='id', how='inner')
df_inner_join

  id  age           job
0  C   25        Doctor
1  D   22  Statistician

In [125]:
#shape
print(df1.shape)
print(df2.shape)
print(df_inner_join.shape)

(4, 2)
(4, 2)
(2, 3)

### 1.1.1 Exercise

In [126]:
# merge the df_movies and df_ratings dataframes (inner join)

In [127]:
df_movies

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium"
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [128]:
df_ratings

      imdb_title_id  total_votes  mean_vote
0         tt0000009          154        5.9
1         tt0000574          589        6.3
2         tt0001892          188        6.0
3         tt0002101          446        5.3
4         tt0002130         2237        6.9
...             ...          ...        ...
85850     tt9908390          398        5.5
85851     tt9911196          724        7.9
85852     tt9911774          265        7.8
85853     tt9914286          194        9.4
85854     tt9914942          102        6.8

[85855 rows x 3 columns]

In [129]:
df_movies.merge(df_ratings, on='imdb_title_id', how='inner')

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [130]:
pd.merge(df_movies, df_ratings, on='imdb_title_id') # works the same as the previous code section

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

### 1.2 Outer join (Full join)

In [131]:
df_outer_join = df1.merge(df2, on='id', how='outer')
df_outer_join

  id   age           job
0  A  30.0           NaN
1  B  23.0           NaN
2  C  25.0        Doctor
3  D  22.0  Statistician
4  E   NaN    Accountant
5  F   NaN     Developer

In [132]:
# shape

print(df1.shape)
print(df2.shape)
print(df_inner_join.shape)
print(df_outer_join.shape)

(4, 2)
(4, 2)
(2, 3)
(6, 3)

### 1.2.1 Exercise

In [133]:
# merge df_movies and df_ratings (outer join)

In [134]:
df_movies.merge(df_ratings, on='imdb_title_id', how='outer')

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

### 1.3 Exclusive Outer join (Exclusive full join)

In [135]:
df1.merge(df2, on='id', how='outer', indicator=True)

  id   age           job      _merge
0  A  30.0           NaN   left_only
1  B  23.0           NaN   left_only
2  C  25.0        Doctor        both
3  D  22.0  Statistician        both
4  E   NaN    Accountant  right_only
5  F   NaN     Developer  right_only

In [136]:
# query

df_exclusive_outer_join = df1.merge(df2, on='id', how='outer', indicator=True).query("_merge=='left_only' or _merge=='right_only'")
df_exclusive_outer_join

  id   age         job      _merge
0  A  30.0         NaN   left_only
1  B  23.0         NaN   left_only
4  E   NaN  Accountant  right_only
5  F   NaN   Developer  right_only

In [137]:
# shape
print(df_exclusive_outer_join.shape)

(4, 4)

### 1.3.1 Exercise

In [138]:
# merge df_movies and df_ratings

df_movies.merge(df_ratings, on='imdb_title_id', how='outer', indicator=True)

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9,both
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3,both
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0,both
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3,both
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9,both
...,...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5,both
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9,both
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8,both
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4,both
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8,both

In [139]:

df_movies.merge(df_ratings, on='imdb_title_id', how='outer', indicator=True).query("_merge=='left_only' or _merge=='right_only'")

Empty DataFrame
Columns: [imdb_title_id, title, year, genre, country, total_votes, mean_vote, _merge]
Index: []

### 1.4 Left join

In [140]:
df1.merge(df2, on='id', how='left')

  id  age           job
0  A   30           NaN
1  B   23           NaN
2  C   25        Doctor
3  D   22  Statistician

### 1.4.1 Exercise

In [141]:
# extract a 50% sample of the df_movies dataframe

df_movies_sample = df_movies.sample(frac=0.5)
df_movies_sample

,imdb_title_id,title,year,genre,country
862,tt0020754,Charley's Aunt,1930,Comedy,USA
10912,tt0055488,Sua Eccellenza si fermò a mangiare,1961,Comedy,Italy
61199,tt1716739,Dead in France,2012,"Comedy, Crime, Thriller",UK
39598,tt0275083,Musa,2001,"Action, Drama, History","South Korea, China"
83708,tt8072400,Hello Guru Prema Kosame,2018,"Comedy, Romance",India
...,...,...,...,...,...
65761,tt2251648,La dune,2013,Drama,"France, Israel"
1909,tt0025524,La mujer del puerto,1934,Drama,Mexico
49513,tt0762104,How to Rob a Bank (and 10 Tips to Actually Get...,2007,"Comedy, Crime, Mystery",USA
69786,tt3092552,Io sono Mateusz,2013,Drama,Poland
17307,tt0074086,40 gradi all'ombra del lenzuolo,1976,Comedy,Italy

In [142]:
# merge df_movies_sample and df_ratings (left join)

df_left = df_movies_sample.merge(df_ratings, on='imdb_title_id', how='left')
df_left

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0020754,Charley's Aunt,1930,Comedy,USA,112,6.4
1,tt0055488,Sua Eccellenza si fermò a mangiare,1961,Comedy,Italy,219,6.7
2,tt1716739,Dead in France,2012,"Comedy, Crime, Thriller",UK,254,6.9
3,tt0275083,Musa,2001,"Action, Drama, History","South Korea, China",10632,7.4
4,tt8072400,Hello Guru Prema Kosame,2018,"Comedy, Romance",India,1637,7.7
...,...,...,...,...,...,...,...
42923,tt2251648,La dune,2013,Drama,"France, Israel",227,6.9
42924,tt0025524,La mujer del puerto,1934,Drama,Mexico,326,7.3
42925,tt0762104,How to Rob a Bank (and 10 Tips to Actually Get...,2007,"Comedy, Crime, Mystery",USA,5874,6.3
42926,tt3092552,Io sono Mateusz,2013,Drama,Poland,2305,7.8
42927,tt0074086,40 gradi all'ombra del lenzuolo,1976,Comedy,Italy,323,5.5

In [143]:
# shape

print(df_movies_sample.shape)
print(df_ratings.shape)
print(df_left.shape)

(42928, 5)
(85855, 3)
(42928, 7)

### 1.5 Exclusive Left join

In [144]:
df1.merge(df2, on='id', how='outer', indicator=True).query("_merge=='left_only'")

  id   age  job     _merge
0  A  30.0  NaN  left_only
1  B  23.0  NaN  left_only

### 1.5.1 Exercise

In [145]:
# make a copy of the df_movies dataframe 

df_movies_2 = df_movies.copy()

df_movies_2

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium"
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [146]:
# set the first 1000 values of 'imdb_title_id' column as tt1234567890

df_movies_2.loc[:999, 'imdb_title_id'] = 'tt1234567890'
df_movies_2

,imdb_title_id,title,year,genre,country
0,tt1234567890,Miss Jerry,1894,Romance,USA
1,tt1234567890,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt1234567890,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt1234567890,Cleopatra,1912,"Drama, History",USA
4,tt1234567890,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium"
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain

In [147]:
# merge df_movies_2 and df_ratings (exclusive left join)

df_exclusive_left = df_movies_2.merge(df_ratings, on='imdb_title_id', how='outer', indicator=True).query("_merge=='left_only'")
df_exclusive_left

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
55817,tt1234567890,Miss Jerry,1894,Romance,USA,NaN,NaN,left_only
55818,tt1234567890,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,NaN,NaN,left_only
55819,tt1234567890,Den sorte drøm,1911,Drama,"Germany, Denmark",NaN,NaN,left_only
55820,tt1234567890,Cleopatra,1912,"Drama, History",USA,NaN,NaN,left_only
55821,tt1234567890,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...
56812,tt1234567890,Agente segreto Z1,1930,Drama,USA,NaN,NaN,left_only
56813,tt1234567890,Tom Sawyer,1930,"Adventure, Comedy, Drama",USA,NaN,NaN,left_only
56814,tt1234567890,Tonka Sibenice,1930,Drama,"Czechoslovakia, Germany",NaN,NaN,left_only
56815,tt1234567890,Top Speed,1930,"Comedy, Musical, Romance",USA,NaN,NaN,left_only
56816,tt1234567890,True to the Navy,1930,"Action, Comedy, Romance",USA,NaN,NaN,left_only

In [148]:
# shape

print(df_exclusive_left.shape)
print(df_movies_2.shape)
print(df_ratings.shape)

(1000, 8)
(85855, 5)
(85855, 3)

### 1. Right Join

In [149]:
df1.merge(df2, on='id', how='right')

  id   age           job
0  C  25.0        Doctor
1  D  22.0  Statistician
2  E   NaN    Accountant
3  F   NaN     Developer

### 1.6.1 Exercise

In [150]:
# extract a 30% sampleof the df_ratings dataframe

df_ratings_sample = df_ratings.sample(frac=0.3)

In [151]:
# merge df_movies and df_ratings_sample (right join)

df_right = df_movies.merge(df_ratings_sample, on='imdb_title_id', how='right')
df_right

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0087964,La notte porta consiglio,1982,Comedy,France,281,5.2
1,tt0031477,Non puoi impedirmi d'amare,1939,"Drama, Romance",USA,2568,7.3
2,tt0286917,Requiem - Labirinto mortale,2001,"Action, Crime, Horror",France,445,5.5
3,tt1590013,Dom över död man,2012,"Biography, Drama","Sweden, Norway",648,6.0
4,tt0090234,Une femme en Afrique,1985,"Drama, Romance",France,110,7.1
...,...,...,...,...,...,...,...
25751,tt2813906,Kashikoi inu wa hoezuni warau,2012,Thriller,Japan,223,6.7
25752,tt0056283,Il prigioniero di Guam,1962,"Drama, War",USA,434,7.0
25753,tt0111366,Tarzan of Manisa,1994,Drama,Turkey,122,6.3
25754,tt3662764,Muska,2014,"Drama, Horror, Thriller",Turkey,467,3.7
25755,tt11052808,Kim Ji-young: Born 1982,2019,Drama,South Korea,1806,7.4

In [152]:
# shape

print(df_ratings_sample.shape)
print(df_movies.shape)
print(df_right.shape)

(25756, 3)
(85855, 5)
(25756, 7)

### 1.7 Exclusive right join

In [153]:
# indicator = True

df1.merge(df2, on='id', how='outer', indicator=True).query("_merge=='right_only'")

  id  age         job      _merge
4  E  NaN  Accountant  right_only
5  F  NaN   Developer  right_only

### 1.7.1 Exercise

In [154]:
# make a copy of the df_ratings dataframe

df_ratings_copy = df_ratings.copy()

In [155]:
# set the first 1000 values of 'imdb_title_id' column as tt1234567890

df_ratings_copy.loc[:999, 'imdb_title_id'] = 'tt1234567890'
df_ratings_copy

      imdb_title_id  total_votes  mean_vote
0      tt1234567890          154        5.9
1      tt1234567890          589        6.3
2      tt1234567890          188        6.0
3      tt1234567890          446        5.3
4      tt1234567890         2237        6.9
...             ...          ...        ...
85850     tt9908390          398        5.5
85851     tt9911196          724        7.9
85852     tt9911774          265        7.8
85853     tt9914286          194        9.4
85854     tt9914942          102        6.8

[85855 rows x 3 columns]

In [160]:
# merge df_movies and df_ratings_2 (exclusive right join)

df_exclusive_right_join = df_movies.merge(df_ratings_copy, on='imdb_title_id', how='outer', indicator=True).query("_merge=='right_only'")
df_exclusive_right_join

,imdb_title_id,title,year,genre,country,total_votes,mean_vote,_merge
55817,tt1234567890,NaN,NaN,NaN,NaN,154.0,5.9,right_only
55818,tt1234567890,NaN,NaN,NaN,NaN,589.0,6.3,right_only
55819,tt1234567890,NaN,NaN,NaN,NaN,188.0,6.0,right_only
55820,tt1234567890,NaN,NaN,NaN,NaN,446.0,5.3,right_only
55821,tt1234567890,NaN,NaN,NaN,NaN,2237.0,6.9,right_only
...,...,...,...,...,...,...,...,...
56812,tt1234567890,NaN,NaN,NaN,NaN,128.0,5.8,right_only
56813,tt1234567890,NaN,NaN,NaN,NaN,160.0,6.6,right_only
56814,tt1234567890,NaN,NaN,NaN,NaN,106.0,7.2,right_only
56815,tt1234567890,NaN,NaN,NaN,NaN,172.0,6.2,right_only
56816,tt1234567890,NaN,NaN,NaN,NaN,103.0,7.0,right_only

In [162]:
# shape

print(df_exclusive_right_join.shape)
print(df_ratings_copy.shape)
print(df_movies.shape)

(1000, 8)
(85855, 3)
(85855, 5)