In [17]:
import pandas as pd

In [18]:
# read csv file
df = pd.read_csv('players_20.csv')

# set index
df.set_index('short_name', inplace=True)

# select necessary columns
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club', 'overall']]

# show dataframe
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91

### 1. Drop Row

In [19]:
# drop one row using:

# 1. axis parameter
df.drop('L. Messi', axis=0)

# OR

# 2. index parameter
df.drop(index=['L. Messi'])

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City,91
...,...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48

In [20]:
# drop two or more rows and update data (inplace=True)

df.drop(['L. Messi', 'Neymar Jr'], inplace=True)
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City,91
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona,90

### 1. Drop Columns

In [21]:
# drop one column using:
# 1. axis parameter
df.drop('age', axis=1)

# OR

# 2. columns parameter
df.drop(columns=['age'])

,long_name,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,1985-02-05,187,83,Portugal,Juventus,93
J. Oblak,Jan Oblak,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,Eden Hazard,1991-01-07,175,74,Belgium,Real Madrid,91
K. De Bruyne,Kevin De Bruyne,1991-06-28,181,70,Belgium,Manchester City,91
M. ter Stegen,Marc-André ter Stegen,1992-04-30,187,85,Germany,FC Barcelona,90
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,1997-03-10,186,79,China PR,Beijing Renhe FC,48
Xiao Mingjie,Mingjie Xiao,1997-01-01,177,66,China PR,Shanghai SIPG FC,48
Zhang Wei,张威,2000-05-16,186,75,China PR,Hebei China Fortune FC,48
Wang Haijian,汪海健,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48
Pan Ximing,潘喜明,1993-01-11,182,78,China PR,Hebei China Fortune FC,48

### 2. Drop columns by position/index

In [22]:
# drop one column
# axis parameter

df.drop('long_name', axis=1)

# or 
# column parameter
df.drop(columns=['long_name'])

,age,dob,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,,
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus,93
J. Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91
E. Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91
K. De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City,91
M. ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona,90
...,...,...,...,...,...,...,...
Shao Shuai,22,1997-03-10,186,79,China PR,Beijing Renhe FC,48
Xiao Mingjie,22,1997-01-01,177,66,China PR,Shanghai SIPG FC,48
Zhang Wei,19,2000-05-16,186,75,China PR,Hebei China Fortune FC,48
Wang Haijian,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC,48
Pan Ximing,26,1993-01-11,182,78,China PR,Hebei China Fortune FC,48

In [23]:
# drop columns by position/index (drop last column)


df.drop(df.columns[[-2]], axis=1)

,long_name,age,dob,height_cm,weight_kg,nationality,overall
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,93
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,91
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,91
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,91
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,90
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,48
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,48
Zhang Wei,张威,19,2000-05-16,186,75,China PR,48
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,48
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,48

In [24]:
# drop two or more columns and update data (inplace=True)

df.drop(['long_name', 'dob'], axis=1, inplace=True)
df

,age,height_cm,weight_kg,nationality,club,overall
short_name,,,,,,
Cristiano Ronaldo,34,187,83,Portugal,Juventus,93
J. Oblak,26,188,87,Slovenia,Atlético Madrid,91
E. Hazard,28,175,74,Belgium,Real Madrid,91
K. De Bruyne,28,181,70,Belgium,Manchester City,91
M. ter Stegen,27,187,85,Germany,FC Barcelona,90
...,...,...,...,...,...,...
Shao Shuai,22,186,79,China PR,Beijing Renhe FC,48
Xiao Mingjie,22,177,66,China PR,Shanghai SIPG FC,48
Zhang Wei,19,186,75,China PR,Hebei China Fortune FC,48
Wang Haijian,18,185,74,China PR,Shanghai Greenland Shenhua FC,48
Pan Ximing,26,182,78,China PR,Hebei China Fortune FC,48